from __future__ import annotations
from abc import ABC, abstractmethod
from typing import Optional, Iterable
from forgetit.core.schema import MemRecord, Query, MemFeatures

# class Backend(Protocol):
#     def connect(self) -> None: ...
#     def close(self) -> None: ...

#     def upsert(self, item: MemRecord) -> None: ...
#     def get(self, item_id: str) -> Optional[MemRecord]: ...
#     def delete(self, item_id: str) -> None: ...

#     def search(self, query: Query, k: int) -> list[MemRecord]: ...
#     def iter_ids(self) -> Iterable[str]: ...



class Backend(ABC):

    @property
    def is_persistent(self) -> bool:
        return False
    
    @abstractmethod
    def connect(self) -> None: ...
    @abstractmethod
    def close(self) -> None: ...

    @abstractmethod
    def upsert(self, item: MemRecord) -> None: ...
    @abstractmethod
    def get(self, item_id: str) -> Optional[MemRecord]: ...
    @abstractmethod
    def delete(self, item_id: str) -> None: ...

    @abstractmethod
    def search(self, query: Query, k: int) -> list[MemRecord]: ...

    @abstractmethod
    def iter_ids(self) -> Iterable[str]: ...

    @abstractmethod
    def scan_accounting(self) -> list[tuple[str, int]]:
        """Return (id, bytes) for all items."""
        ...
    
    @abstractmethod
    def scan_features(self) -> Iterable[MemFeatures]:
        """
        Yield eviction-relevant features for all items.
        """
        ...